### ISSUE TITLE
Odd scroll bar behaviour with more button

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react#14]
Hey TQ

When on the Homepage of the wallet and the "more" button isn't expanded, there is a scroll bar on my page:

![image](https://user-images.githubusercontent.com/22153546/42282261-3bfe06fa-7fa6-11e8-9be2-ed986cb9bf39.png)

However, when I click on More, it takes away my scroll bar which is kinda weird.

![image](https://user-images.githubusercontent.com/22153546/42282294-517578ce-7fa6-11e8-9c17-094731aa997b.png)

**Comment by TarCode** [comment]
Been testing on multiple browsers this side and cannot replicate. That screenshot also seems to be from an older version, so please test and lemme know if this is still happenin' :)
