### ISSUE TITLE
Adjust upload ID UI for 'proof of' UI

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react#49]
Hey T

It's been great iterating on this modal, I think we're getting close. Please make these changes:

1. Change the field name `Proof upload` to say `Document upload`
2. Move the Upload button to be left aligned with the field name. 
3. Ensure that the button is spaced properly from the field name. It should be the same spacing which is between the line you see beneath "ID or passport noo." and "Issue date" field.
4. Remove the placeholder image entirely.
5. Make the uploaded document appear beneath the fields instead of next to them. (You can see how landscape vs portrait can display)
6. Extend the field lines so they reach the right end of the Submit button.
7. Change the `Upload` button to say `Choose file`.

![image](https://user-images.githubusercontent.com/22153546/46754886-e5bf2b00-ccc3-11e8-863f-6affcd6f5d25.png)

**Comment by TarCode** [comment]
1 and 2 fixed, number 3 left for separate button colour issue (last)

**Comment by Cupofassam** [comment]
👌
