### ISSUE TITLE
Add 'View transaction' button to txn success modal

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react#69]
Hey T :)

Please add a 'View transaction' button to the left of the OKAY button in the transaction success modal

![image](https://user-images.githubusercontent.com/22153546/47021811-767e8680-d15c-11e8-9aa3-d1838db9ee6e.png)

**Comment by Cupofassam** [comment]
Not seeing this button on prod!

**Comment by TarCode** [comment]
Coz it wasn't. Lolz. Was on master. Hahaha

**Comment by Cupofassam** [comment]
xD
