### ISSUE TITLE
Add account name and balances to currency selector on Send screen

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react#75]
Hey T

Having a currency selector on the send screen is really cool, but can get confusing if there is a use case where a user has multiple accounts with the same currency:

![image](https://user-images.githubusercontent.com/22153546/47309061-c2856b80-d633-11e8-8879-4161272b6e09.png)

On the app Matthew shows the currency code, the account name and the balance of the account when selecting a currency - please implement this same thing on the web wallet :) You can use the same format too

![whatsapp image 2018-10-22 at 19 49 44](https://user-images.githubusercontent.com/22153546/47309091-daf58600-d633-11e8-976e-f1a0f428361d.jpeg)

**Comment by Cupofassam** [comment]
Cool :) this works well!

One change - when we display the selected currency on the send screen (i.e. after a user has selected, and the list with account name and balance is closed) we can just display the currency code - we don't need to display the account name and the balance on the send modal when we're not selecting a currency.

So the currency and amount can go back next to each other rather than being on separate lines.

**Comment by TarCode** [comment]
This is updated - I managed to test on Android and Mac Chrome and seems to be aligned. But you'll have to check on Windows and lemme know

**Comment by Cupofassam** [comment]
This is great :) felt very intuitive to use

it is still slightly misaligned on Windows (just to be difficult, lol) The currency field is like 1px higher than the amount field.

Another thing - the currency field can maybe be a bit shorter. Even with a long currency there's plenty of space, and sometimes amounts are very long:. Maybe take out a chunk about the size of this red square:

![image](https://user-images.githubusercontent.com/22153546/47430896-ed3e0400-d79a-11e8-815a-c463709840ab.png)

**Comment by Cupofassam** [comment]
👌
